"""
Redis Streams event queue publisher.
Single instance per process; connection pooled via redis-py async client.
"""
import json
from functools import lru_cache
from uuid import UUID
from redis.asyncio import Redis, ConnectionPool
from app.core.config import settings
from app.core.logging import get_logger

logger = get_logger(__name__)


@lru_cache(maxsize=1)
def _get_pool() -> ConnectionPool:
    return ConnectionPool.from_url(settings.redis_url, decode_responses=True)


def get_redis() -> Redis:
    """Returns a Redis client backed by the shared connection pool."""
    return Redis(connection_pool=_get_pool())


class EventQueuePublisher:
    """
    Publishes payment events to a Redis Stream.
    Each message gets a unique stream ID generated by Redis (auto-ID via '*').
    """

    def __init__(self, stream: str = settings.redis_stream_name):
        self.stream = stream
        self._redis = get_redis()

    async def publish_payment_event(self, event_id: UUID, payment_id: str, payload: dict) -> str:
        """
        Publishes a payment event to the stream.
        Returns the Redis stream message ID.
        """
        message = {
            "event_id": str(event_id),
            "payment_id": payment_id,
            "event_type": "payment.failed",
            "payload": json.dumps(payload),
        }
        try:
            stream_id = await self._redis.xadd(self.stream, message)
            logger.info(f"message=Event published | stream={self.stream} | stream_id={stream_id} | payment_id={payment_id}")
            return stream_id
        except Exception as e:
            logger.warning(f"message=Redis queue publishing skipped ({e}) | payment_id={payment_id}")
            return None

    async def ensure_consumer_group(self) -> None:
        """Creates the consumer group if it doesn't exist (idempotent)."""
        try:
            await self._redis.xgroup_create(
                self.stream, settings.redis_stream_consumer_group, id="0", mkstream=True
            )
            logger.info(f"message=Consumer group created | group={settings.redis_stream_consumer_group}")
        except Exception as e:
            if "BUSYGROUP" in str(e):
                pass  # already exists — expected on restart
            else:
                raise

    async def close(self) -> None:
        await self._redis.aclose()


# Module-level singleton — shared across requests
_publisher: EventQueuePublisher | None = None


def get_publisher() -> EventQueuePublisher:
    global _publisher
    if _publisher is None:
        _publisher = EventQueuePublisher()
    return _publisher
