"""
All enums for the Revenue Recovery Engine.
Single source of truth — imported by schemas, models, and agents.
"""
from enum import StrEnum


class FailureCause(StrEnum):
    TEMPORARY_FAILURE = "TEMPORARY_FAILURE"
    INSUFFICIENT_FUNDS = "INSUFFICIENT_FUNDS"
    PAYMENT_METHOD_FAILURE = "PAYMENT_METHOD_FAILURE"
    CUSTOMER_ABANDONMENT = "CUSTOMER_ABANDONMENT"
    EXPIRED_PAYMENT = "EXPIRED_PAYMENT"
    RISK_REJECTION = "RISK_REJECTION"
    UNKNOWN = "UNKNOWN"


class ActionType(StrEnum):
    RETRY = "RETRY"
    PAYMENT_LINK = "PAYMENT_LINK"
    REMINDER = "REMINDER"
    NO_ACTION = "NO_ACTION"
    HUMAN_ESCALATION = "HUMAN_ESCALATION"


class Priority(StrEnum):
    HIGH = "HIGH"
    MEDIUM = "MEDIUM"
    LOW = "LOW"


class WorkflowStatus(StrEnum):
    PENDING = "PENDING"
    DIAGNOSING = "DIAGNOSING"
    DIAGNOSED = "DIAGNOSED"
    STRATEGY_SELECTED = "STRATEGY_SELECTED"
    AWAITING_POLICY = "AWAITING_POLICY"
    AWAITING_APPROVAL = "AWAITING_APPROVAL"
    EXECUTING = "EXECUTING"
    OBSERVING = "OBSERVING"
    RECOVERED = "RECOVERED"
    FAILED = "FAILED"
    ESCALATED = "ESCALATED"
    ABANDONED = "ABANDONED"
    NOT_ELIGIBLE = "NOT_ELIGIBLE"
    POLICY_REJECTED = "POLICY_REJECTED"


class InterventionStatus(StrEnum):
    PENDING = "PENDING"
    EXECUTING = "EXECUTING"
    SUCCEEDED = "SUCCEEDED"
    FAILED = "FAILED"
    CANCELLED = "CANCELLED"


class ExperimentGroup(StrEnum):
    TREATMENT = "TREATMENT"
    CONTROL = "CONTROL"


class OpportunityStatus(StrEnum):
    OPEN = "OPEN"
    DIAGNOSING = "DIAGNOSING"
    DIAGNOSED = "DIAGNOSED"
    STRATEGY_SELECTED = "STRATEGY_SELECTED"
    AWAITING_POLICY = "AWAITING_POLICY"
    AWAITING_APPROVAL = "AWAITING_APPROVAL"
    IN_PROGRESS = "IN_PROGRESS"
    EXECUTING = "EXECUTING"
    RECOVERED = "RECOVERED"
    FAILED = "FAILED"
    POLICY_REJECTED = "POLICY_REJECTED"
    ABANDONED = "ABANDONED"


class PaymentMethod(StrEnum):
    CARD = "CARD"
    UPI = "UPI"
    NETBANKING = "NETBANKING"
    WALLET = "WALLET"
    EMI = "EMI"
    OTHER = "OTHER"
